name       : openjdk-17
version    : 17.0.2
release    : 1
source     :
    - https://github.com/openjdk/jdk17u/archive/refs/tags/jdk-17.0.2-ga.tar.gz : f7b1540b12d72ca4710376292b6084fac13819a90bcaa1e5e81734c1b3b09517
    - https://github.com/adoptium/temurin17-binaries/releases/download/jdk-17.0.2%2B8/OpenJDK17U-jdk_x64_linux_hotspot_17.0.2_8.tar.gz : 288f34e3ba8a4838605636485d0365ce23e57d5f2f68997ac4c2e4c01967cd48
license    : GPL-2.0-only WITH Classpath-exception-2.0
component  : programming.java
homepage   : https://openjdk.java.net/
summary    : Open implementation of Oracle's Java Development Kit, major version 17
description: |
    Open implementation of Oracle's Java Development Kit, major version 17. This package includes both the JDK and its accompanying JRE.
ccache     : no
clang      : yes
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(fontconfig)
    - pkgconfig(lcms2)
    - pkgconfig(libjpeg)
    - pkgconfig(x11)
    - pkgconfig(xext)
    - pkgconfig(xrandr)
    - pkgconfig(xrender)
    - pkgconfig(xt)
    - pkgconfig(xtst)
    - pkgconfig(xxf86vm)
    - cups-devel
    - giflib-devel
setup      : |
    tar xvzf $sources/OpenJDK17U-jdk_x64_linux_hotspot_17.0.2_8.tar.gz -C $workdir

    %patch -p1 < $pkgfiles/0001-Double-default-reserved-code-cache-size.patch
    %patch -p1 < $pkgfiles/0001-Enable-tiered-compilation.patch
    %patch -p1 < $pkgfiles/0001-Use-current-directory-as-backup-for-user-prefs.patch
    %patch -p1 < $pkgfiles/0001-Dont-echo-_JAVA_OPTIONS.patch

    chmod +x configure
    %configure --prefix="$installdir/usr" \
        --with-jvm-variants=client \
        --with-boot-jdk=$workdir/jdk-17.0.2+8 \
        --with-native-debug-symbols=internal \
        --with-toolchain-type=clang \
        --with-version-pre="" \
        --with-version-opt="solus" \
        --with-stdc++lib=dynamic \
        --with-freetype=system \
        --with-giflib=system \
        --with-harfbuzz=system \
        --with-lcms=system \
        --with-libjpeg=system \
        --with-libpng=system \
        --with-zlib=system \
        --enable-unlimited-crypto \
        --disable-warnings-as-errors \
        --disable-absolute-paths-in-output \
        --with-extra-cflags="${CFLAGS}" \
        --with-extra-cxxflags="${CXXFLAGS}" \
        --with-extra-ldflags="${LDFLAGS}" \
        --with-jobs=%YJOBS%
build      : |
    # Build OpenJDK and JRE
    make images legacy-jre-image
install    : |
    install -Ddm00755 $installdir/%libdir%/
    install -dm00755 $installdir/usr/include/openjdk-17/
    install -dm00755 $installdir/usr/share/applications/

    make install

    # Binaries
    mv $installdir/usr/jvm/openjdk-* $installdir/%libdir%/openjdk-17/
    rm -rf $installdir/usr/jvm/
    rm -rf $installdir/usr/bin/

    # Remove license files and demo files
    rm -rf $installdir/%libdir%/openjdk-17/{legal,demo}/

    # Headers
    cd build/linux-x86_64-*/
    cp -ar jdk/include/* $installdir/usr/include/openjdk-17/
    # Symlink header files (because some apps look for them in $JAVA_HOME)
    ln -s /usr/include/openjdk-17/ $installdir/%libdir%/openjdk-17/include/
    # Man pages
    mv $installdir/%libdir%/openjdk-17/man/ $installdir/usr/share/
    find $installdir/usr/share/man/ -type f -exec rename -- ".1" "-17.1" {} \;

    # Add java-17-jar.desktop into usable apps
    install -Dm 00644 $pkgfiles/java-17-jar.desktop $installdir/usr/share/applications/
# check      : |
# TODO add jtreg to repos so we can run JDK test harness
#     make test-only TEST="gtest:all"
