name       : openjdk-17
version    : 17.0.3
release    : 2
source     :
    - https://github.com/openjdk/jdk17u/archive/refs/tags/jdk-17.0.3-ga.tar.gz : 9a23da36c4e8f26a7197c6e6b763c7be83bc8788f495ae9dadfabadf8c7d57c2
license    : GPL-2.0-only WITH Classpath-exception-2.0
component  : programming.java
homepage   : https://openjdk.java.net/
summary    : Open implementation of Oracle's Java Development Kit, major version 17
description: |
    Open implementation of Oracle's Java Development Kit, major version 17. This package includes both the JDK and its accompanying JRE.
ccache     : no
clang      : yes
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(fontconfig)
    - pkgconfig(lcms2)
    - pkgconfig(libjpeg)
    - pkgconfig(x11)
    - pkgconfig(xext)
    - pkgconfig(xrandr)
    - pkgconfig(xrender)
    - pkgconfig(xt)
    - pkgconfig(xtst)
    - pkgconfig(xxf86vm)
    - cups-devel
    - giflib-devel
    - jtreg
    - openjdk-17
setup      : |
    %patch -p1 < $pkgfiles/0001-Double-default-reserved-code-cache-size.patch
    %patch -p1 < $pkgfiles/0001-Enable-tiered-compilation.patch
    %patch -p1 < $pkgfiles/0001-Use-current-directory-as-backup-for-user-prefs.patch
    %patch -p1 < $pkgfiles/0001-Dont-echo-_JAVA_OPTIONS.patch

    chmod +x configure
    %configure --prefix="$installdir/usr" \
        --with-jvm-variants=client \
        --with-boot-jdk="/usr/lib64/openjdk-17" \
        --with-native-debug-symbols=internal \
        --with-toolchain-type=clang \
        --with-version-build="7" \
        --with-version-pre="" \
        --with-version-opt="solus" \
        --with-stdc++lib=dynamic \
        --with-freetype=system \
        --with-giflib=system \
        --with-harfbuzz=system \
        --with-jtreg=/usr/share/jtreg \
        --with-lcms=system \
        --with-libjpeg=system \
        --with-libpng=system \
        --with-zlib=system \
        --enable-unlimited-crypto \
        --disable-warnings-as-errors \
        --disable-absolute-paths-in-output \
        --with-extra-cflags="${CFLAGS}" \
        --with-extra-cxxflags="${CXXFLAGS}" \
        --with-extra-ldflags="${LDFLAGS}" \
        --with-jobs=%YJOBS%
build      : |
    # Build OpenJDK and JRE
    make images legacy-jre-image
install    : |
    install -Ddm00755 $installdir/%libdir%/
    install -dm00755 $installdir/usr/include/openjdk-17/
    install -dm00755 $installdir/usr/share/applications/

    make install

    # Binaries
    mv $installdir/usr/jvm/openjdk-* $installdir/%libdir%/openjdk-17/
    rm -rf $installdir/usr/jvm/
    rm -rf $installdir/usr/bin/

    # Remove license files and demo files
    rm -rf $installdir/%libdir%/openjdk-17/{legal,demo}/

    # Headers
    cd build/linux-x86_64-*/
    cp -ar jdk/include/* $installdir/usr/include/openjdk-17/
    # Symlink header files (because some apps look for them in $JAVA_HOME)
    ln -s /usr/include/openjdk-17/ $installdir/%libdir%/openjdk-17/include/
    # Man pages
    mv $installdir/%libdir%/openjdk-17/man/ $installdir/usr/share/
    find $installdir/usr/share/man/ -type f -exec rename -- ".1" "-17.1" {} \;

    # Add java-17-jar.desktop into usable apps
    install -Dm 00644 $pkgfiles/java-17-jar.desktop $installdir/usr/share/applications/
# check      : |
    # make test-tier1
